/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* TASK SCHEDULER:
 * - Tasks runs in Thread mode using PSP.
 * - Scheduler (SysTick handler) runs in Handler mode using MSP.
 * - Each task has its own private stack.
 * - exception entry sequences auto store R0-R3, R12, LR, PC, PSR.
 * - scheduler will save the context state by also saving R4-R11 and PSP.
 * M4:
 * - 128kb of RAM (SRAM1 + SRAM2) each task gets (1kb this is an arbitrary choice).
 * - Stack is full descending
 * SCHEDULING POLICY:
 * - scheduler is the SysTick handler
 * - round robin pre-emptive scheduling.
 * - no task priority
 * - SysTick timer will generate an exception every 1ms to run the scheduler code.
 *
 * */
#include"main.h"
#include"led.h"

int main(void)
{
	enable_processor_faults();

	init_scheduler_stack(SCHED_STACK_START);

	init_task_stacks();

	led_init_all();

	init_systick_timer(TICK_HZ); 									// set SysTick exception to every 1ms.

	switch_sp_to_psp();

	task1_handler();

    /* Loop forever */
	for(;;);
}

/*Scheduler: performs context switching between multiple tasks using PendSV.
 * Update global tick count and blocked states needing updated.
 * */
void SysTick_Handler(void)
{
	uint32_t *pICSR = (uint32_t*)0xE000ED04;

	update_global_tick_count();
	unblock_tasks();
	*pICSR |= ( 1 << 28); 										// pend the PendSV exception.
}

__attribute__((naked)) void PendSV_Handler(void)
{
	/*Save content of current task to its private stack*/
	__asm volatile("MRS R0, PSP");								// get current tasks PSP value.
	__asm volatile("STMDB R0!, {R4-R11}");						// store SF2 R4-11 (SF1 is auto stored)(Store multiple decrement before)

	__asm volatile("PUSH {LR}");								// save LR before branch with link

	__asm volatile("BL save_psp_value");                        // store current tasks PSP value (R0 already has current PSP)

	/*Retrieve context of next task*/
	__asm volatile("BL update_next_task");
	__asm volatile("BL get_psp_value");
	__asm volatile("LDMIA R0!, {R4-R11}");						// retrieve SF2 (R4 to R11) (load multiple increment after)
	__asm volatile("MSR PSP, R0");								// update PSP: now points to area of "next task"

	/*Exit handler to next task*/
	__asm volatile("POP {LR}");									// restore LR
	__asm volatile("BX LR");									// manual exception exit because this is a naked function

}

void update_global_tick_count(void)
{
	global_tick_count ++;
}

/*check tasks that are due to be unblocked. idle task always runs so its never considered*/
void unblock_tasks(void)
{
	for (int i=1; i<MAX_TASKS; i++)
	{
		if (user_tasks[i].current_state != TASK_READY_STATE)
		{
			if (user_tasks[i].block_count == global_tick_count)
			{
				user_tasks[i].current_state = TASK_READY_STATE;
			}
		}
	}
}

void task_delay(uint32_t tick_count)
{	// disable interrupt: protects global variable access
	INTERRUPT_DISABLE();

	if(current_task)     // if idle task do nothing.
	{
		user_tasks[current_task].block_count = global_tick_count + tick_count;  // block until global tick count reaches this.
		user_tasks[current_task].current_state = TASK_BLOCKED_STATE;
		schedule();															// allow other task to run
	}

	// enable interrupt
	INTERRUPT_ENABLE();
}

void schedule(void)
{
	uint32_t *pICSR = (uint32_t*)0xE000ED04;
	*pICSR |= ( 1 << 28); 										// pend the PendSV exception.
}

uint32_t get_psp_value(void)
{
	return user_tasks[current_task].psp_value;
}

void save_psp_value(uint32_t current_psp_value)
{
	user_tasks[current_task].psp_value = current_psp_value;
}

void update_next_task(void)
{
	int state = TASK_BLOCKED_STATE;

	for(int i=0; i<MAX_TASKS; i++)
	{
		current_task++;
		current_task %= MAX_TASKS;
		state = user_tasks[current_task].current_state;
		if( (state == TASK_READY_STATE) && (current_task != 0) )
		{
			break;
		}
	}
	if (state != TASK_READY_STATE)
	{
		current_task = 0;
	}
}

__attribute__((naked)) void switch_sp_to_psp(void)
{
	//1. init PSP with task1 stack start.
	__asm volatile("PUSH {LR}");						// preserve return to main.
	__asm volatile ("BL get_psp_value");				// edit LR.
	__asm volatile ("MSR PSP, R0");						// address task 1 stack start PSP (init PSP)
	__asm volatile ("POP {LR}");						// restore return to main.
	//2. change SP to PSP using control reg.
	__asm volatile ("MOV R0, #0X02");
	__asm volatile ("MSR CONTROL, R0");
	__asm volatile ("BX LR");
}

/*init MSP for scheduler stack*/
__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack)
{	/*MSR: move to special register. MSP: main stack pointer. "r"(sched_top_of_stack) read that value into R0
	(prolly already there because it was the first arg of the function). sched_top_of_stack is moved to MSP.
	this is done so to begin manual init of the schedulers stack. */
	__asm volatile("MSR MSP, R0"::"r"(sched_top_of_stack):);
	__asm volatile("BX LR");										// Branch indirect back to return to main
}

/*
 * A. Init Task states.
 * B. Init dummy stacks for each task. SPRs, GPRs, and save each tasks PSP.
*/
void init_task_stacks(void)
{
	// A.1. all tasks are initially in running state.
	for (int i = 0; i < MAX_TASKS; i++)
	{
		user_tasks[i].current_state = TASK_READY_STATE;
	}

	// A.2. initialize PSP value for tasks
	user_tasks[0].psp_value = IDLE_STACK_START;
	user_tasks[1].psp_value = T1_STACK_START;
	user_tasks[2].psp_value = T2_STACK_START;
	user_tasks[3].psp_value = T3_STACK_START;
	user_tasks[4].psp_value = T4_STACK_START;

	// A.3. initialize task handler pointer arr
	user_tasks[0].task_handler = idle_task;
	user_tasks[1].task_handler = task1_handler;
	user_tasks[2].task_handler = task2_handler;
	user_tasks[3].task_handler = task3_handler;
	user_tasks[4].task_handler = task4_handler;

	// B. make dummy stacks
	uint32_t *pPSP;
	for (int i=0; i < MAX_TASKS; i++)
	{
		//SF1: special registers
		pPSP = (uint32_t*) user_tasks[i].psp_value;  					// at start of tasks private stack
		pPSP--;															// xPSR
		*pPSP = DUMMY_XPSR;
		pPSP--;															// PC
		*pPSP = (uint32_t)user_tasks[i].task_handler;					// address of LSB must be odd because of T bit.
		pPSP--;															// LR
		*pPSP = 0xFFFFFFFD;

		for (int j=0; j<13; j++)							// the rest of SF1 and SF2 is just GPRs that need to be set to 0
		{
			pPSP--;
			*pPSP = 0;
		}
		user_tasks[i].psp_value = (uint32_t)pPSP;						// store new PSP
	}
}

void init_systick_timer(uint32_t tick_hz)
{
	uint32_t *pSRVR = (uint32_t*)SYSTICK_RVR;            				// reload value register
	uint32_t *pSCSR = (uint32_t*)SYSTICK_CSR;							// control and status register
	uint32_t count_value = ( (SYSTICK_TIM_CLK) / (tick_hz) ) - 1; 		// reload value calculation

	// load into SRVR
	*pSRVR &= ~(0x00FFFFFF);
	*pSRVR |= count_value;

	// configure control and status register (CLKSOURCE AND TICKINT set to 1)
	*pSCSR |= (1 << 1);                                                 // enable TICKINT (SysTick exception request)
	*pSCSR |= (1 << 2);													// enable CLKSOURCE (indicates clock source)

	// enable SysTick
	*pSCSR |= (1 << 0);													// enables counter
}

/*LED4 Green every one second*/
void task1_handler(void)
{
	printf("Task 1: Green\n");
	while(1)
	{
		led_on(LED_GREEN);
		task_delay(1000);
		led_off(LED_GREEN);
		task_delay(1000);
	}
}

/*LED3 Orange every 500ms*/
void task2_handler(void)
{
	printf("Task 2: Orange\n");
	while(1)
	{
		led_on(LED_ORANGE);
		task_delay(500);
		led_off(LED_ORANGE);
		task_delay(500);
	}
}

/*LED5 Red every 250ms*/
void task3_handler(void)
{
	printf("Task 3: Red\n");
	while(1)
	{
		led_on(LED_RED);
		task_delay(250);
		led_off(LED_RED);
		task_delay(250);
	}
}

/*LED6 Blue every 125ms*/
void task4_handler(void)
{
	printf("Task 4: Blue\n");
	while(1)
	{
		led_on(LED_BLUE);
		task_delay(125);
		led_off(LED_BLUE);
		task_delay(125);
	}
}

/*always running state*/
void idle_task(void)
{
	while(1);
}

void enable_processor_faults(void)
{
	//Enable all configurable exceptions (MemManage, Bus, and Usage)
	uint32_t *pSHCSR = (uint32_t*) (0xE000ED24);        // pointer to system handler control and state register

	*pSHCSR |= (1 << 16);     // enable MemManage
	*pSHCSR |= (1 << 17);     // enable Bus
	*pSHCSR |= (1 << 18);     // enable Usage
}

void HardFault_Handler(void)
{
	printf("Exception : HardFault\n");
	while(1);
}

void MemManage_Handler(void)
{
	printf("Exception : MemManageFault\n");
		while(1);
}

void BusFault_Handler(void)
{
	printf("Exception : BusFault\n");
		while(1);
}


